### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by bmorse1** [mplinuxgeek/ds2mqtt#1]
After following the install steps I am trying to run ds2mqtt. I am getting command not found.

pi@pitemp-1:/opt/ds2mqtt $ cd /opt/ds2mqtt/
pi@pitemp-1:/opt/ds2mqtt $ ds2mqtt
-bash: ds2mqtt: command not found

**Comment by bmorse1** [comment]
I just had to use the whole path to run it.

pi@pitemp-1:/opt/ds2mqtt $ /opt/ds2mqtt/ds2mqtt
06/18/2020 02:53:58 PM - ds2mqtt - INFO - Connecting to 192.168.1.30
06/18/2020 02:53:58 PM - ds2mqtt - INFO - Connection successful
06/18/2020 02:53:58 PM - ds2mqtt - INFO - Found 1 sensors
06/18/2020 02:53:59 PM - ds2mqtt - INFO - Publishing sensor 01192efe3927 (DS18B20), temperature: -8.61▒F
06/18/2020 02:53:59 PM - ds2mqtt - INFO - Sleeping for 120 seconds

**Comment by mplinuxgeek** [comment]
The script isn't in the path so you either need to use the whole path or prefix it with ./ when you are in the directory, ie ./ds2mqtt

**Comment by mplinuxgeek** [comment]
And that was my fault, I left out the ./ in the instructions, fixed now, sorry for inconvenience.
